version: '2'
services:
  # The Application
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
  # The Web Server
  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
  # The Database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pinbucket
    volumes:
      - postgres-data:/var/lib/postgresql/data/pinbucket

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"

volumes:
  postgres-data: